### ISSUE TITLE
Previous button does not work after users click on "next page".

### ISSUE THREAD

**Issue by Safery** [Safery/Rothshi#3]
The issue comes from the Manga chapter view.html page.

**Comment by fukouda** [comment]
Do you think the problem lies with `prev_page()` in manga.js?

**Comment by Safery** [comment]
> Do you think the problem lies with prev_page() in manga.js?

I think the problem lies on how functions `Next_Page()` and `Prev_Page()`. The functions work by getting the first selected option and moves to previous or next option. The problem is, If the original selected option was started at "0", I call `Next_Page()` and the page picture was changed to "1". But this did not update the page so `Prev_Page()` function still believes the select option was still at "0". Therefore, when users clicks on "Previous Page" button, it gets an error because it is trying to go to the previous 'page' of a non selected value.

Its hard to explain but imagine like this:
- User clicks on Page 3.
- Next_Page() and Prev_Page() both thinks the select option started at Page 3.
- User clicks Next_Page and the image was changed to Page 4. But the html page did not update to "page 4", it only updated the image.
- When users clicks Prev_Page(), it won't work because Prev_Page() is trying to go to Page 2 (It believes the user is viewing Page 3, but in-reality, User is viewing Page 4).

One way to fix this issue is having both function keep track of value of each images every-time new page is generated. I will fix it later on, because I am going to hate debugging the part of code.

**Comment by Safery** [comment]
minor issue, won't need fix. The button still works, won't cause any performance issue or user usability issue.
